export const levels = [
  {
    level: 1,
    rows: 3,
    cols: 4,
    timeLimit: 60,
    totalCards: 12,
    hasShuffle: true,
    matchPairs: [
      { artist: "Bad Bunny", title: "Monaco" },
      { artist: "Billie Eilish", title: "Birds of a Feather" },
      { artist: "Kendrick Lamar", title: "Not Like Us" },
      { artist: "Post Malone", title: "I Had Some Help" },
      { artist: "Taylor Swift", title: "Cruel Summer" },
      { artist: "The Weeknd", title: "Blinding Lights" },
    ],
  },
  {
    level: 2,
    rows: 3,
    cols: 6,
    timeLimit: 90,
    totalCards: 18,
    hasShuffle: true,
    hasCombo: true,
    matchPairs: [
      { artist: "Bruno Mars", title: "Die With A Smile" },
      { artist: "Sabrina Carpenter", title: "Espresso" },
      { artist: "Stray Kids", title: "Chk Chk Boom" },
      { artist: "SZA", title: "Snooze" },
      { artist: "Dua Lipa", title: "Houdini" },
      { artist: "Olivia Rodrigo", title: "Vampire" },
      { artist: "Drake", title: "God's Plan" },
      { artist: "Miley Cyrus", title: "Flowers" },
      { artist: "Harry Styles", title: "As It Was" },
    ],
  },
  {
    level: 3,
    rows: 4,
    cols: 7,
    timeLimit: 120,
    totalCards: 28,
    hasShuffle: true,
    hasCombo: true,
    matchPairs: [
      { artist: "Chappell Roan", title: "Good Luck, Babe!" },
      { artist: "Beyoncé", title: "TEXAS HOLD 'EM" },
      { artist: "Doja Cat", title: "Paint The Town Red" },
      { artist: "Ariana Grande", title: "We Can't Be Friends" },
      { artist: "NewJeans", title: "Super Shy" },
      { artist: "Travis Scott", title: "FE!N" },
      { artist: "Lady Gaga", title: "Disease" },
      { artist: "Eminem", title: "Rap God" },
      { artist: "Rihanna", title: "Lift Me Up" },
      { artist: "Green Day", title: "American Idiot" },
      { artist: "Queen", title: "Bohemian Rhapsody" },
      { artist: "Coldplay", title: "Yellow" },
      { artist: "Big Bang", title: "Bang Bang Bang" },
      { artist: "Ed Sheeran", title: "Shivers" },
    ],
  },
];

export const personas = [
  {
    name: "The Soundwave Sage",
    message: "You don’t just listen. You live in surround sound.",
    description: `Music is your oxygen. You’ve got playlists for moods you haven’t even felt yet. New drops? Already saved. Deep cuts? Already looping. Your algorithm bows to you. You discover trends first.`,
    img: "./Assets/Persona1.png",
    minScore: 80,
    percentage: "80-100%",
  },
  {
    name: "The Beat Devotee",
    message: "Your life has a solid soundtrack.",
    description: `You show up for the music. Commutes, workouts, late nights — you’ve got a curated vibe ready. You revisit favorites but still explore enough to keep things fresh. You’re loyal… but not predictable.`,
    img: "./Assets/Persona2.png",
    minScore: 60,
    percentage: "60-79%",
  },
  {
    name: "The Rhythm Rover",
    message: "You surf the soundwaves.",
    description: `You dip in when the mood hits. Some days it’s nonstop streaming, other days it’s radio silence. You lean into trending tracks, viral hits, and curated playlists. Music finds you more than you hunt for it.`,
    img: "./Assets/Persona3.png",
    minScore: 40,
    percentage: "40-59%",
  },
  {
    name: "The Silent Mode Starter",
    message: "Your ears deserve better.",
    description: `You’ve got potential. Your account is warming up, but your speakers are waiting. This is your sign to press play more often. The soundtrack of your life? Still buffering.`,
    img: "./Assets/Persona4.png",
    minScore: 0,
    percentage: "0-39%",
  },
];

export const buttonMenu = {
  mainMenu: [
    { id: "play", text: "Play" },
    { id: "how-to", text: "How to Play", type: "hover" },
  ],
  winOverlay: [{ id: "next", text: "Next Level" }],
  lostOverlay: [{ id: "retry", text: "Try Again" }],
  victoryOverlay: [{ id: "result", text: "View Results" }],
  resultOverlay: [
    { id: "download", text: "Download" },
    { id: "share", text: "Share" },
  ],
};
